- hosts: "{{ host | default('incorta') }}"
  remote_user: incorta  
  become: yes
  tasks:

  - name: Update yum
    yum:
      update_cache: yes
      

  - name: Append the public key to authorized_keys
    lineinfile:
      path: /home/incorta/.ssh/authorized_keys
      line: "{{ lookup('file', '../key.pub') }}"


  - name: Copy Oracle JDK 8 installer 
    copy:
      src: ../jdk-8u301-linux-x64.rpm
      dest: /opt
      mode: 0755


  - name: Install Oracle JDK 8
    shell:
      cmd: rpm -ivh jdk-8u301-linux-x64.rpm
      chdir: /opt
    ignore_errors: True


  - name: Add "JAVA_HOME" to ".bashrc"
    lineinfile:
      path: /home/incorta/.bashrc
      line: "export JAVA_HOME=/usr/java/jdk1.8.0_301-amd64"

      


  
